transaction_types = {
    "FundsCharge": "Safaricom Charges",
    "Funds Charge": "Safaricom Charges",
    "Customer Transfer": "Send money",
    "Funds received": "Receive money",
    "Send Money Reversal": "Reversal",
    "Recharge": "Airtime",
    "Airtime Purchase": "Airtime",
    "Customer Bundle Purchase": "Airtime",
    "Buy Bundles": "Airtime",
    "Pay Bill Charge": "Safaricom Charges",
    "Pay Bill": "Paybill",
    "Customer Payment to Small": "Pochi la Biashara",
    "Merchant Payment": "Buy Goods",
    "Business Payment": "Receive money from bank/org",
    "Receive funds": "Receive money from bank/org",
    "Transfer from Bank": "Receive money from bank/org",
    "IMTReceive": "International Money Transfer Receipt",
    "Receive International": "International Money Transfer Receipt",
    "Send Money Abroad": "International Money Transfer Sent",
    "Customer Withdrawal": "Withdraw Money",
    "Deposit": "Deposit Cash",
    "M-Shwari Loan": "M-Shwari Loan",
    "M-Shwari": "M-Shwari",
    "Withdrawal Charge": "Safaricom Charges",
    "IMT Send Charge": "Safaricom Charges",
    "Pay Merchant Charge": "Safaricom Charges",
    "Daraja": "Daraja",
    "": "Unidentified",
}
